Redo mod-printer with additional whiteout lpstat info
ocf/utils pull request #177
Opened 2022-03-03 00:50 UTC by Boomaa23

As it turns out if you run `lpstat` on whiteout it gives you more information about the non-shared printers (for example, `logjam-single` instead of just `single`). Thus this is a re-write of the `mod-printer` script which makes fewer assumptions and implements an actual parsed status/list command.

2022-03-05 04:09 UTC, dkess requested changes
Sorry for the late review! Left some comments.

2022-03-05 04:09 UTC, dkess commented on staff/lab/mod-printer
> +        class_arg = (args.classname and args.classname in printer_name) or not args.classname
These two lines (and how they connect to the next if statement) are hard to understand. I'd recommend splitting it up something like this:

```py
if printer and printer not in printer_name:
  continue

if args.classname and args.classname not in printer_name:
  continue

if printer_name not in cups_classes:
  all_printers.append(printer_name)
```

This way it's easy to see where we skip and what the criteria it is that the code is looking for.

2022-03-05 04:27 UTC, Boomaa23 commented on staff/lab/mod-printer
> +    printer = args.printer and args.printer.lower()
If `args.printer` is `None`, won't this throw an error?

2022-03-05 04:33 UTC, Boomaa23 commented on staff/lab/mod-printer
> +    for class_name, class_members in cups_classes.items():
oooh I didn't even know this was a thing in Python, I will use.

2022-03-05 04:41 UTC, Boomaa23 commented on staff/lab/mod-printer
> +            print('\nCurrent print jobs:')
Ah I think I prefer `\n` and in this case it's more "symmetrical" in a way with the next line so I think I will keep it.

2022-03-05 19:47 UTC, dkess commented on staff/lab/mod-printer
> +    printer = args.printer and args.printer.lower()
Hmm OK, I guess that's fine.

2022-03-06 03:28 UTC, dkess approved these changes

2022-03-12 02:14 UTC, merged